
results_dir: myopic

weather_dir: weather

html_dir: html

start_date: 2022-01-01
end_date: yesterday

countries: [DE]

time_zone:
  DE: Europe/Berlin

vre_techs: [pv, onshore, offshore]

# in MWh
soc_start:
  DE:
    battery_energy: 5.0e3
    hydrogen_energy: 5.0e7


# in GW or GWh
# from https://www.energy-charts.info/charts/installed_power/chart.htm
historical_capacities:
  DE:
    2022-01-01:
      onshore : 55.9
      pv : 60.1
      offshore : 7.8
    2022-12-31:
      onshore : 58.0
      pv : 67.6
      offshore : 8.2
    2023-12-30:
      onshore : 60.7
      pv : 80.7
      offshore : 8.4


solver_logfile: myopic.log
#order of preference
solver_names: [gurobi,cbc]
solver_options:
  gurobi:
    BarConvTol: 1.0e-08
    crossover: 0
    method: 2
    threads: 4
  highs:
    threads: 4
  cbc:
    threads: 4

numerical_threshold: 1.e-2

weeks_to_plot: 10

color:
  battery_charger: '#999999'
  battery_discharger: '#999999'
  hydrogen_electrolyser: cyan
  hydrogen_turbine: red
  load: k
  load-shedding: k
  offshore: '#5D83A4'
  onshore: '#3B6182'
  pv: '#FFFF00'
