
results_dir: results

weather_dir: weather

html_dir: html

start_date: 2015-01-01
end_date: yesterday

force_restart_date: none

countries: [DE]

time_zone:
  DE: Europe/Berlin

vre_techs: [pv, onshore, offshore, hydro]


# in GW or GWh
# from https://www.energy-charts.info/charts/installed_power/chart.htm
historical_capacities:
  DE:
    2014-12-31:
      onshore : 37.6
      pv : 37.9
      offshore : 1.
      hydro: 4.0
    2015-12-31:
      onshore : 41.3
      pv : 39.2
      offshore : 3.3
      hydro: 3.9
    2016-12-31:
      onshore : 45.3
      pv : 40.7
      offshore : 4.2
      hydro: 4.0
    2017-12-31:
      onshore : 50.2
      pv : 42.3
      offshore : 5.4
      hydro: 3.8
    2018-12-31:
      onshore : 52.3
      pv : 45.2
      offshore : 6.4
      hydro: 3.9
    2019-12-31:
      onshore : 53.2
      pv : 48.9
      offshore : 7.6
      hydro: 4.9
    2020-12-31:
      onshore : 54.3
      pv : 54.4
      offshore : 7.8
      hydro: 4.9
    2021-12-31:
      onshore : 55.9
      pv : 60.1
      offshore : 7.8
      hydro: 4.9
    2022-12-31:
      onshore : 58.0
      pv : 67.6
      offshore : 8.2
      hydro: 4.9
    2023-12-30:
      onshore : 60.7
      pv : 80.7
      offshore : 8.4
      hydro: 4.9

#https://www.gesetze-im-internet.de/eeg_2014/__4.html
targets:
  DE:
    2030:
      onshore: 115
      pv: 215
      offshore: 30
    2040:
      onshore: 160
      pv: 400
      offshore: 55-60



solver_logfile: myopic.log
#order of preference
solver_names: [gurobi,cbc]
solver_options:
  gurobi:
    BarConvTol: 1.0e-08
    crossover: 0
    method: 2
    threads: 4
  highs:
    threads: 4
    solver: ipm
    run_crossover: "off"
    small_matrix_value: 1e-6
    large_matrix_value: 1e9
    primal_feasibility_tolerance: 1e-5
    dual_feasibility_tolerance: 1e-5
    ipm_optimality_tolerance: 1e-4
    parallel: "on"
    random_seed: 123

  cbc:
    threads: 4

numerical_threshold: 1.e-2

weeks_to_plot: 10

days_to_plot: 10

preferred_scenario_order: [default, lessvre, lowwind, nowind, elastic]

color:
  battery_charger: '#999999'
  battery_discharger: '#999999'
  battery_energy: '#999999'
  hydrogen_electrolyser: cyan
  hydrogen_turbine: red
  hydrogen_energy: magenta
  load: k
  load_shedding: k
  load_decrease: '#ff99ff'
  load_increase: '#ff99ff'
  offshore: '#5D83A4'
  onshore: '#3B6182'
  pv: '#FFFF00'
  hydro: green
  pumped_hydro_charger: '#DAF7A6'
  pumped_hydro_discharger: '#DAF7A6'
  pumped_hydro_energy: '#DAF7A6'
  conventional: '#834333'
  other: '#834333'
  bev_demand: '#40E0D0'
  heat_pumps: '#90EE90'

# short-term storage (e.g. battery or pumped hydro) SOC at end of day will be valued
# by this multiplied with hydrogen turbine output value
# it's less than one so that H2 turbine from current day is displaced rather than tomorrow
dayahead_discount_factor: 0.9

# daily mean temperature below which there is space heating [C]
heating_temperature_threshold: 15

# hot water fraction of heating demand
hot_water_fraction: 0.25

# [C]
heat_pump_supply_temperature: 45

# [kW_el]
heat_pump_power: 5

# [MWh_th/a]
heat_pump_demand_yearly: 20

# [MWh_el/a]
bev_demand_yearly: 2
